### ISSUE TITLE
Any changes in dataset with AVDC

### ISSUE THREAD

**Issue by Whalesong-zrs** [Video-as-Agent/VideoAgent#1]
Thanks for your code! I note that some channges in metaworld loading in this code base compared with AVDC, some path 'trajectory_' here, any changes in this new dataset?

**Comment by TrickyJustice** [comment]
Thank you for raising this issue! We did make some adjustments in loading the dataset compared to the baseline approach. In the AVDC codebase, the dataloader randomly samples 7-frame trajectories directly from the dataset during loading. However, this approach does not work for us, as we require a saved (offline) version of the trajectories to generate feedback and store the refined videos. To address this, we created an offline version of the dataset, which contains pre-sampled 7-frame trajectories from the original dataset.

**Comment by Whalesong-zrs** [comment]
> Thank you for raising this issue! We did make some adjustments in loading the dataset compared to the baseline approach. In the AVDC codebase, the dataloader randomly samples 7-frame trajectories directly from the dataset during loading. However, this approach does not work for us, as we require a saved (offline) version of the trajectories to generate feedback and store the refined videos. To address this, we created an offline version of the dataset, which contains pre-sampled 7-frame trajectories from the original dataset.

Thanks a a lot for your reply! I wonder if the offline dataset and the feedback will be realsed recently, or maybe until this work be accepted?

**Comment by TrickyJustice** [comment]
I have added a sample_dataset_generation.py file to the codebase. This script can be used to generate an offline version of the dataset used in our work. You can run this code once you have the initial dataset used by AVDC. We have added the dataset generation script to our experiment repository (https://github.com/Video-as-Agent/VideoAgent_exp). Note that for training, we use only 5 seeds compared to the 25 seeds used for testing.

Additionally, it is labeled as a sample file because, by default, the code samples frames with initial dense sampling, followed by sparser sampling for the remaining frames. For consistency with the dataset used in our work—which includes three types of sampling (initial dense frame sampling, uniform sampling, and end dense sampling)—you can adjust the initial_dense_factor and decrease_factor values in the code.

As for feedback, we have already released the code for generating binary/suggestive feedbacks. These can be found in /flowdiffusion/feedback_binary_rf.py and /flowdiffusion/feedback_mw_extend.py.

**Comment by Whalesong-zrs** [comment]
Thanks a lot! I will try the code carefully. : D

**Comment by Whalesong-zrs** [comment]
I found that in VideoAgent_exp you provide a script about generate metaworld data (python experiment/collect_dataset_mw.py). I wonder if you generate new data yourserlf or you used the dataset same as AVDC, only different in sample process. If you re-render the data your self, could you please share me a copy of mw dataset?
In feedback scripts, I found that some image_paths and gif_paths need to be pre-defined, I wonder that how can I get these files, and when we get feedbacks from openai, only these files enough?

**Comment by TrickyJustice** [comment]
We generate the same dataset used by AVDC, and you can access it via this [link](https://drive.google.com/file/d/1LLvUh5e8qQ4xQr4bjR-s6tyyY4MdyAg5/view). As far as I remember, this is the exact version of the dataset used by AVDC.
Regarding the feedback files, we provide those files in our experiments repository. You can access them [here](https://github.com/Video-as-Agent/VideoAgent_exp/tree/main/flowdiffusion/flowdiffusion/feedback_fewshot).

**Comment by Whalesong-zrs** [comment]
> We generate the same dataset used by AVDC, and you can access it via this [link](https://drive.google.com/file/d/1LLvUh5e8qQ4xQr4bjR-s6tyyY4MdyAg5/view). As far as I remember, this is the exact version of the dataset used by AVDC. Regarding the feedback files, we provide those files in our experiments repository. You can access them [here](https://github.com/Video-as-Agent/VideoAgent_exp/tree/main/flowdiffusion/flowdiffusion/feedback_fewshot).

OK, thanks a lot.

**Comment by Whalesong-zrs** [comment]
Here I note that in VideoAgent_exp/flowdiffusion/flowdiffusion/feedback_binary_rf.py, line 31, show your api key, maybe you need to hide this.

**Comment by TrickyJustice** [comment]
.

**Comment by Whalesong-zrs** [comment]
> .

Sorry to disturb you again, I wonder that every trajectory need to get feedback through VLM, by few-shot query(through the example you provide)?

**Comment by TrickyJustice** [comment]
Yes, feedbacks are required for every trajectory if you are using VideoAgent-Suggestive.

**Comment by Whalesong-zrs** [comment]
I wonder that if you could share the processed metaworld dataset. I process this data as your code, however, some trajectories I made are seven consecutive frames show no visible change to the naked eye.

**Comment by TrickyJustice** [comment]
I checked the code again but couldn't determine the exact cause of this issue. However, I've made the code a bit more robust to handle cases where trajectories near the end show little to no visible change. In these cases, the only reliable indicator of motion across frames may be the image filenames.

As for why we include trajectories with minimal motion, it's because the model needs to learn from a full range of motion and starting points. This includes trajectories that start just before an item is picked up and those that are close to task completion. This diverse range helps the model build a more comprehensive understanding of all stages of motion.

We will make the dataset public as soon as the work is accepted! I hope this answers your queries.

**Comment by Whalesong-zrs** [comment]
> I checked the code again but couldn't determine the exact cause of this issue. However, I've made the code a bit more robust to handle cases where trajectories near the end show little to no visible change. In these cases, the only reliable indicator of motion across frames may be the image filenames.
> 
> As for why we include trajectories with minimal motion, it's because the model needs to learn from a full range of motion and starting points. This includes trajectories that start just before an item is picked up and those that are close to task completion. This diverse range helps the model build a more comprehensive understanding of all stages of motion.
> 
> We will make the dataset public as soon as the work is accepted! I hope this answers your queries.

Thanks a lot! My core question is that why the trajectories near the end show little to no visible change. I will try this.
