### ISSUE TITLE
Some questions about dataset.

### ISSUE THREAD

**Issue by Whalesong-zrs** [Video-as-Agent/VideoAgent#3]
I apologize for the delay in reaching out. Due to some personal matters, I have only recently started working on reproducing the experiment results. However, I have encountered an issue related to the dataset, specifically in the flowdiffusion/dataset.py file around lines 264-265.

I am having trouble understanding how to obtain the file frame_000_video_cond_long_feedback_306.gif that is referenced in this part of the code. Could you please clarify the process or provide any additional information on how this file is generated or where I can find it?

**Comment by TrickyJustice** [comment]
Thank you for reaching out. Since our work conditions on videos generated during previous iterations, these videos represent exactly that. For example, if we are performing the first iteration, we condition on the videos generated by the AVDC baseline. For the second iteration, we condition on the videos generated by the first iteration checkpoint.

To achieve this, we first generated videos from the AVDC baseline for the entire dataset and saved them in their corresponding trajectory files. For the next iterations, we generated videos using the checkpoint obtained from the first iteration and so on.

**Comment by Whalesong-zrs** [comment]
> Thank you for reaching out. Since our work conditions on videos generated during previous iterations, these videos represent exactly that. For example, if we are performing the first iteration, we condition on the videos generated by the AVDC baseline. For the second iteration, we condition on the videos generated by the first iteration checkpoint.
> 
> To achieve this, we first generated videos from the AVDC baseline for the entire dataset and saved them in their corresponding trajectory files. For the next iterations, we generated videos using the checkpoint obtained from the first iteration and so on.

OK，I get it, thanks a lot.

**Comment by Whalesong-zrs** [comment]
I have a follow-up question regarding the sample_per_seq parameter in the sample_dataset_generation.py file. In the script, sample_per_seq is set to 7, but I was wondering if it should be set to 8 instead.

**Comment by TrickyJustice** [comment]
In datasets.py, the default value of samples_per_seq is set to 7 but when we call the dataloader in train_mw.py, we assign samples_per_seq to 8.

**Comment by Whalesong-zrs** [comment]
What I mean is that when generating the trajectories, each trajectory only contains 7 frames, which seems unreasonable.

**Comment by TrickyJustice** [comment]
You are absolutely right. I completely overlooked this typo, thanks for bringing this up. I rewrote the sampling script when you asked me to upload this script in your first issue, and somehow I wrote 7 instead of 8 based on my response in that issue. Thanks a lot of pointing this out, I have updated the sampling script now. Every trajectory contains 8 frames: first frame is the input frame and the rest are output frames.

**Comment by Whalesong-zrs** [comment]
As the number of sampled frames increases, the number of resulting trajectories decreases. Therefore, I would like to know the approximate size of your dataset (i.e., the number of trajectories).

**Comment by TrickyJustice** [comment]
As I mentioned previously, we use three different sampling techniques: initial dense sampling, uniform sampling and end dense sampling. Overall, the approximate number of trajectories were approximately around 4-4.5k. The code can generate more trajectories but to handle class imbalance, the total trajectory count reduced.

**Comment by Whalesong-zrs** [comment]
Thanks a lot. I will try this.
